### ISSUE TITLE
Is the class Namespace necessary?

### ISSUE THREAD

**Issue by cclauss** [671620616/PhantomChess#12]
The comments say:

```python
# 99% of use for this class is a dictionary that doesnt
# raise errors when it doesn't contain an object, but returns None instead
class Namespace (PhantomObj):
```

That functionality can be found in the `dict.get()` method as in: `x = my_dict.get('y', None)`

**Comment by 671620616** [comment]
Probably not - when I first implemented it I used it like

```python
data = Namespace()
data.foo = 2
print data.foo + 2
```

But then I had the issue of raising `AttributeError`s when something I tried to access didn't exist. So I went and added the `data['foo']` behavior as well. The main reason I haven't removed it yet is that I'm lazy - however I'll probably manage it for v0.8.0.

**Comment by cclauss** [comment]
Makes sense.

**Comment by cclauss** [comment]
It might also be useful to look at [collections.defaultdict](https://docs.python.org/2/library/collections.html#collections.defaultdict).

**Comment by 671620616** [comment]
As of commit d0261c85088a35eda5807c80814943caf3487aaa, I have removed all uses of the class that I could find and replaced them with a dict.  Everything seemed to run fine, however I have left the class definition in place just in case we need to revert for some reason.
