### ISSUE TITLE
Run_this.py throws TypeError exception

### ISSUE THREAD

**Issue by cclauss** [671620616/PhantomChess#25]
On line 28, `game = ChessGame()`, the exception is `TypeError: 'NoneType' object is not callable`.

This happens on a clean install.  I can not find the cause of this issue.

**Comment by cclauss** [comment]
Are you seeing this behavior or is it just me?!?

**Comment by cclauss** [comment]
`Piece.type_from_char()` is missing the Bishop -- my mistake.  Sorry!

**Comment by 671620616** [comment]
Merged pull requests #30 and #35.
