### ISSUE TITLE
Unable to commit

### ISSUE THREAD

**Issue by 671620616** [671620616/PhantomChess#42]
Apologies for the lack of updates - GitHub won't let me commit as there is a conflict in multiple files.  I think I may end up having to manually resolve them all, might be a while before I can commit again.

**Comment by 671620616** [comment]
Can commit now - I had to re-clone the repo to my computer because GitHub decided I was too far behind and had file conflicts when I didnt.  A quick clone and then some manual merges did the trick.

**Comment by cclauss** [comment]
Awesome!!
