### ISSUE TITLE
Recursion error in Run_this.py

### ISSUE THREAD

**Issue by 671620616** [671620616/PhantomChess#43]
I am experiencing an error:

```python
RuntimeError: maximum recursion depth exceeded while getting the str of an object
```

whenever I try to do something.

Latest commit, iOS 8.1.2, Pythonista v0.5

**Comment by cclauss** [comment]
Is there a way to roll back to an earlier version before this issue was introduced?

I think I need to learn proper debugging techniques in a tool like PyCharm Community Edition so I can find these kind of bugs faster without resorting to millions of print statements.

For me, finding these the source of this issue is also complicated by the presence of exc_catch() and call_trace() which complicate the frames when exceptions are thrown.  Is there an easy way to turn off exc_catch() during development?

**Comment by 671620616** [comment]
I have a backup version from 20150330 - although that might be a little too old.  

As for the debugger, if I'm on Windows I like to use [Spyder][0] from the Anaconda bundle.  However, in Phantom, rather than just using tons of `print 'foo'` a safer way could be to do something like:

```python
from Phantom.utils.debug import log_msg
log_msg('foo', 3)
```

This will only print the message `'foo'` if the Phantom debug level is set to 3 or above in the Phantom.constants file.

Exc_catch() currently does not have an off switch, although if I'm going to do a rollback to an earlier version I could definitely implement something like the `log_msg` auto-off-if-debug-set-to-x.  That would allow us to just put the debug up to 4 or 5 and not have exc_catch() hiding anything.

[0]:https://store.continuum.io/cshop/anaconda/

**Comment by 671620616** [comment]
However, I think I have managed to trace the error to one particular issue (and it's a massive traceback): somewhere, it's trying to do `int('m')`.  I suspect it's in `Pawn.apply_ruleset()` with the bit that checks for en passant moves.

Full traceback:

```python
ValueError: invalid literal for int() with base 10: 'm'

Traceback (most recent call last):
  File "run_tests.py", line 42, in <module>
    main()

  File "run_tests.py", line 38, in main
    m.main(False)

  File "/var/ ... Phantom/boardio/epd_read.py", line 185, in load_test
    return load_epd(load_test_string(name))

  File "/var/ ... Phantom/boardio/epd_read.py", line 156, in load_epd
    b = Board(fen=fen)

  File "/var/ ... Phantom/core/board.py", line 130, in __init__
    newpiece = klass(pos, color, owner)

  File "/var/ ... Phantom/core/pieces.py", line 75, in __init__
    self.subvalidcache = self.update_cache()

  File "/var/ ... Phantom/utils/debug.py", line 90, in wrapped
    returned = f(*args, **kwargs)

  File "/var/ ... Phantom/core/pieces/py", line 192, in update_cache
    return [tile.coord for tile in self.owner.board.tiles
               if self.apply_ruleset(tile.coord)]

  File "/var/ ... Phantom/utils/debug.py", line 90, in wrapped
    returned = f(*args, **kwargs)

  File "/var/ ... Phantom/core/pieces.py", line 226, in apply_ruleset
    elif Coord.from_chess(self.owner.board.en_passant_rights) in tests:

  File "/var/ ... Phantom/core/coord/point.py", line 150, in from_chess
    y = int(chess[1])
```

**Comment by 671620616** [comment]
Found the issue: in Phantom.boardio.epd_read, it's trying to convert 'hmvc' into a chess coordinate.  So the bug is in fact in the epd reader. Will get to fixing ASAP.

**Comment by cclauss** [comment]
You might roll back this Pull Request... https://github.com/671620616/PhantomChess/commit/b76526a14e2512219dceeb9149528ff12b16b04e

I probably screwed thing up there.

**Comment by 671620616** [comment]
The issue has been fixed - there were two things wrong:
1. there was a small issue in epd_read.py
2. I missed entering the en passant field in the "checkmate test 1" self-test, which made the reader unhappy.  Will upload a fix now.

Having now fixed that error, we can now move on to fix the recursion error that I originally created the issue about.  (joys of programming - fix one thing, break another)

**Comment by cclauss** [comment]
Great news.  The project currently has two branches: master, and pull-0.  If you accept the pull-0 changes or you delete the pull-0 branch, does that free things up so that you can make commits again?

If not, you could email changes to me then I could make a pull request that you could approve.  It is strange that I can propose changes but you can not.

**Comment by 671620616** [comment]
The issue appears to be in the `Phantom.ChessPiece.__str__` method, at least that seems to be the most recurrent thing in the tracebacks I'm getting.  I'm wondering if the threats/threatened by list that is created also calls pieces' `__str__`, which would lead to a recursion error.

**Comment by 671620616** [comment]
Also, @cclauss, I have implemented the suggessted auto-off switch in the `exc_catch` decorator, the level at which it deactivates can be changed in the `Phantom.constants` file.

**Comment by 671620616** [comment]
Issue is fixed and commited - you were correct in commit 79e3218 that using the name __str__ causes loops, it has been reverted to as_str().
