### ISSUE TITLE
KeyError on kill

### ISSUE THREAD

**Issue by cclauss** [671620616/PhantomChess#49]
```
:> a2a4
:> b7b5
:> a4b5
### !exc_catch: caught an unpassed exception - KeyError:
    <pawn at (1, 4) in 0x1030961d0>
```

**Comment by 671620616** [comment]
I have to admit I have known about this for some time but neglected to try to fix it because it wasn't
actually causing me any issues - it was just happening, and stuff moved on.  I also have to admit I have
absolutely no idea why it's happening, but if I had to guess I'd say it's in the `Board.kill` method.  Will
investigate further.

**Comment by 671620616** [comment]
In fact, after profiling the following:

```python
import Phantom
g = Phantom.ChessGame()
g.move('e2e4')
g.move('f7f5')
g.move('e4f5')
```

the `Board.kill()` method was called 6 times instead of 1 as I would expect.

**Comment by cclauss** [comment]
How do you disable the exc_catch decorator?  I edited constants.py to change the values of `debug` and `exc_catch_cutoff` but exc_catch() always seems to be evoked.

**Comment by cclauss** [comment]
The KeyError is generated for the square where the killer was before the move, not where he is after he has killed his opponent.  I would still love to know how you disable the exc_catch decorator!

**Comment by cclauss** [comment]
hint: A piece at coord(7,7) ('h8') has pieces to its se()  and nw() which is not correct.

**Comment by 671620616** [comment]
When you say they have pieces to the nw(), do you mean the list generated by nw(piece) is not empty or that there are actually pieces there?

**Comment by cclauss** [comment]
the list generated by nw(piece) is not empty

**Comment by cclauss** [comment]
I did a huge rewrite to change a bunch of things and get rid o Coord.  I think it will be much easier to wrap our minds around the new approach and it will be easier to add support for other GUIs. 

I will push the code in the next 24 hours.

**Comment by cclauss** [comment]
Fixed in Refactor
