### ISSUE TITLE
use_unicode = True causes exceptions on Macs

### ISSUE THREAD

**Issue by cclauss** [671620616/PhantomChess#50]
A series of exceptions are thrown when `use_unicode` is True in `constants.py` when running both `python Phantom/Run_this.py` and `pypy Phantom/Run_this.py` on Macs yet it works flawlessly on Pythonista for iOS.

**Comment by cclauss** [comment]
Partially fixed: set `use_unicode` to True in `constants.py` and then `python Phantom/core/board.py` to see a unicode chess board...

```
      Chess
–––––––––––––––––––
  a b c d e f g h   
8 ♜ ♞ ♝ ♛ ♚ ♝ ♞ ♜ 8 
7 ♟ ♟ ♟ ♟ ♟ ♟ ♟ ♟ 7 
6 ◦ • ◦ • ◦ • ◦ • 6 
5 • ◦ • ◦ • ◦ • ◦ 5 
4 ◦ • ◦ • ◦ • ◦ • 4 
3 • ◦ • ◦ • ◦ • ◦ 3 
2 ♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙ 2 
1 ♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖ 1 ◀ 
  a b c d e f g h
```
Phantom/Run_this.py does __NOT__ work yet.

**Comment by 671620616** [comment]
Issue is fixed but at least on Windows rebuilding and running Run_this.py opens in a command prompt window, which does not support unicode.  Also, it seems to me that most platforms other than Pythonista don't use monospace chess characters, which tends to throw off the `Board._pprnt()` function, as it relies on a monospace font.  In fact, on Windows, Run_this.exe doesn't work at all.  I will assume that unicode works on OSx and implement some platform tests based on what knowledge we have gained about which platforms allow successful use of unicode vs. which don't.  The use_unicode setting can then be set to whether the platform supports unicode or not as needed.

**Comment by cclauss** [comment]
See https://github.com/cclauss/uncategorized_hacks/commit/ed6e2373326a395a9eddb73cef45935a222baa63 for full Max OSX results...

```
platform.platform() ==> Darwin-14.3.0-x86_64-i386-64bit  # Mac OSX
platform.platform() ==> Darwin-14.0.0.0-iPad3,4-32bit     # iOS
```

On Windows, can you set the default font of terminal/powershell to be a monospaced font?

**Comment by cclauss** [comment]
The final solution was to try printing a welcome message containing unicode characters in `can_print_unicode()` and to catch the UnicodeEncodeError if it is thrown.

Does this solution work for the Windows Simple.exe and for running in Spyder on WIndows?

**Comment by 671620616** [comment]
This solution half works and half doesn't work - in Spyder, here is the result:
![spyder-screenshot][0]  (if you can't see it, the characters printed but aren't monospaced)
In Simple.exe, as far as I could tell it didn't display any unicode characters.  Everything worked as 
intended there.

[0]: https://drive.google.com/file/d/0B8JcwRV_HVk0RDFrVWVtdDFXVFE/view?usp=sharing

**Comment by cclauss** [comment]
I am interested to see if the platform module can help us to distinguish Spyder from other environments.  Can you please run https://github.com/cclauss/uncategorized_hacks/blob/master/platform_hack.py in:

* a Windows pyinstaller app
* Spyder
* Windows terminal (DOS, PowerShell, etc.) by typing `python platform_hack`

Also, are there any configuration settings in Spyder that allow you to set the output font?

**Comment by cclauss** [comment]
I am closing this because the current code now allows unicode to be turned on in PyInstaller-generated apps as well as in Python and Pypy on the Mac.  This is despite the fact that PyInstaller does not properly set sys.stdout.encoding to 'UTF-8' as it should.  See https://github.com/pyinstaller/pyinstaller/pull/1243

**Comment by 671620616** [comment]
Sorry to get back so late - lots of homework & driver's ed.  
On Spyder:
```python
[2] >>> runfile('C:/Users/Misha/Documents/Python_workdir/platform_hack.py', wdir='C:/Users/Misha/Documents/Python_workdir')
Please upgrade to a real computer and then press any key to continue...
-------------------------------- = ...
platform.architecture()          = ('32bit', 'WindowsPE')
platform.machine()               = AMD64
platform.node()                  = DellXPSMisha
platform.platform()              = Windows-8-6.2.9200
platform.processor()             = Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
platform.python_build()          = ('default', 'Jul  2 2014 15:13:35')
platform.python_compiler()       = MSC v.1500 32 bit (Intel)
platform.python_branch()         = 
platform.python_implementation() = CPython
platform.python_revision()       = 
platform.python_version()        = 2.7.8
platform.python_version_tuple()  = ('2', '7', '8')
platform.release()               = 8
platform.system()                = Windows
platform.version()               = 6.2.9200
platform.uname()                 = ('Windows', 'DellXPSMisha', '8', '6.2.9200', 'AMD64', 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')
--------------------------------
('Windows', '8', '6.2.9200')
Windows
8
6.2.9200
--------------------------------
```

On Windows Terminal (`python platform_hack`):
```python
[2] >>> runfile('C:/Users/Misha/Documents/Python_workdir/platform_hack.py', wdir='C:/Users/Misha/Documents/Python_workdir')
Please upgrade to a real computer and then press any key to continue...
-------------------------------- = ...
platform.architecture()          = ('32bit', 'WindowsPE')
platform.machine()               = AMD64
platform.node()                  = DellXPSMisha
platform.platform()              = Windows-8-6.2.9200
platform.processor()             = Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
platform.python_build()          = ('default', 'Jul  2 2014 15:13:35')
platform.python_compiler()       = MSC v.1500 32 bit (Intel)
platform.python_branch()         = 
platform.python_implementation() = CPython
platform.python_revision()       = 
platform.python_version()        = 2.7.8
platform.python_version_tuple()  = ('2', '7', '8')
platform.release()               = 8
platform.system()                = Windows
platform.version()               = 6.2.9200
platform.uname()                 = ('Windows', 'DellXPSMisha', '8', '6.2.9200', 'AMD64', 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')
--------------------------------
('Windows', '8', '6.2.9200')
Windows
8
6.2.9200
--------------------------------
```
(identical to Spyder)

And finally a PyInstaller exe:
```python
[2] >>> runfile('C:/Users/Misha/Documents/Python_workdir/platform_hack.py', wdir='C:/Users/Misha/Documents/Python_workdir')
Please upgrade to a real computer and then press any key to continue...
-------------------------------- = ...
platform.architecture()          = ('32bit', 'WindowsPE')
platform.machine()               = AMD64
platform.node()                  = DellXPSMisha
platform.platform()              = Windows-8-6.2.9200
platform.processor()             = Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
platform.python_build()          = ('default', 'Jul  2 2014 15:13:35')
platform.python_compiler()       = MSC v.1500 32 bit (Intel)
platform.python_branch()         = 
platform.python_implementation() = CPython
platform.python_revision()       = 
platform.python_version()        = 2.7.8
platform.python_version_tuple()  = ('2', '7', '8')
platform.release()               = 8
platform.system()                = Windows
platform.version()               = 6.2.9200
platform.uname()                 = ('Windows', 'DellXPSMisha', '8', '6.2.9200', 'AMD64', 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')
--------------------------------
('Windows', '8', '6.2.9200')
Windows
8
6.2.9200
--------------------------------
```
(once again, identical.)

**Comment by cclauss** [comment]
What do you get in Windows Terminal when you type: `python -c "import sys ; print(sys.stdout.encoding)"`

**Comment by 671620616** [comment]
```python
$ python -c "import sys ; print(sys.stdout.encoding)"
cp437
```

**Comment by cclauss** [comment]
In the past few days I have been hacking with a free Python editor called PyCharm 4.0 Community Edition and it suggests fixes for all kinda things so that is where this round of changes came from.  It hooks nicely into GitHub so that edits on my Mac can be pushed into the repo.  Works well and the `Inspect Code` features are quite helpful.

The debugger in is seems cool but I need to learn it more in detail.  I would really love to get instructions from you on how to turn off the exception catching in Phantom.

**Comment by 671620616** [comment]
In order to turn off exception catching (with commit 78d00266426af551bf9230adbf7f6a141d717227), 
all you (should) have to do is go to the `constants` file and change two values:

1.)  On line 38, `debug` to whatever you want (10 makes it pretty slow but you get ***everything*** logged)
2.) On line 58, `exc_catch_cutoff` is the value at which exception catching is disabled.  So if `debug > exc_catch_cutoff`, then the exception catcher decorator simply returns the function it was given:

```python
def __call__(self, f):
        retval = self.ret
        name = self.name or f.__name__

        if debug > exc_catch_cutoff:
            return f
```

**Comment by cclauss** [comment]
OK...  I will try that on Monday when I am back at my Mac.

One last request, can you edit `can_print_unicode.py` to turn Unicode on and tell me how it now looks on Windows in a normal run and in a pyinstaller .exe?  I did stuff that makes Unicode work on the Mac with no exceptions and proper spacing. However I am not sure if those mods will help the Windows situation or not.

**Comment by 671620616** [comment]
Two different, unexpected and confusing results from the new definition of `can_print_unicode.py`:
```python
def can_print_unicode():
    if not os.getenv('PYTHONIOENCODING', None):  # PyInstaller workaround
        os.environ['PYTHONIOENCODING'] = 'utf_8'
    return True
    try:
        print(u'♜ ♞ ♝  {} ♗ ♘ ♖ '.format(s).encode('utf-8'))
        return (sys.stdout.encoding == 'UTF-8' and sys.platform == 'darwin')  # True  # FIXME
    except UnicodeEncodeError:
        print(str(s))
        return False
```

In Spyder I get a `UnicodeError`:
```
[5] >>> runfile('C:/Users/Misha/Documents/Python_workdir/PhantomChess/Phantom/Run_this.py', wdir='C:/Users/Misha/Documents/Python_workdir/PhantomChess/Phantom')
PhantomChess Copyright (C) 2015 671620616
This program comes with ABSOLUTELY NO WARRANTY; for details enter 'license'
This is free software, and you are welcome to redistribute it
under certain conditions; type 'license' for details.

Your game can be displayed by typing 'game'
To move, type 'e2e4' or similar.
To execute a function, simply type the function as you normally would.
To exit, type 'quit' or close the program.
For a full list of commands, type 'help'.
Traceback (most recent call last):

  File "<ipython-input-5-a690fb06ed61>", line 1, in <module>
    runfile('C:/Users/Misha/Documents/Python_workdir/PhantomChess/Phantom/Run_this.py', wdir='C:/Users/Misha/Documents/Python_workdir/PhantomChess/Phantom')

  File "C:\Users\Misha\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 580, in runfile
    execfile(filename, namespace)

  File "C:/Users/Misha/Documents/Python_workdir/PhantomChess/Phantom/Run_this.py", line 42, in <module>
    print(game)

  File "C:\Users\Misha\Anaconda\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)

UnicodeEncodeError: 'charmap' codec can't encode character u'\u265c' in position 57: character maps to <undefined>
```

And the PyInstaller app just simply won't use unicode.  I have no idea why.  No matter what I change, I can't get rid of the SAN characters.

**Comment by cclauss** [comment]
OK.  That helps.  Try moving the `return True` line down two lines so it is just after the `print(u'♜ ♞ ♝  {} ♗ ♘ ♖ '.format(s).encode('utf-8'))` line.  That print line has the effect of "priming the pump" my sending some Unicode characters to the terminal with a particular encoding.  Once you have completed that experiment the I can submit a new version that.

**Comment by 671620616** [comment]
After changing to
```python
def can_print_unicode(s='Welcome to PhantomChess...'):
    if not os.getenv('PYTHONIOENCODING', None):  # PyInstaller workaround
        os.environ['PYTHONIOENCODING'] = 'utf_8'
    try:
        print(u'♜ ♞ ♝  {} ♗ ♘ ♖ '.format(s).encode('utf-8'))
        return True
        return (sys.stdout.encoding == 'UTF-8' and sys.platform == 'darwin')  # True  # FIXME
    except UnicodeEncodeError:
        print(str(s))
        return False
```
 Spyder prints unicode characters but not monospaced, Simple.exe just won't do it, and in the command prompt (`$ python Run_this.py`) it prints something that certainly isn't chess pieces, but I don't know exactly *what* it is.

**Comment by cclauss** [comment]
Try changing the second 'UTF-8' to 'CP437' which should your default `sys.stdout.encoding`.
