### ISSUE TITLE
Simple.exe for Mac?

### ISSUE THREAD

**Issue by 671620616** [671620616/PhantomChess#51]
From my *extremely* limited experience on a Mac, I don't know of a way to run files that end in `.exe`.  This means that for users on a mac, the uploaded `Simple.exe` is completely useless.  What file extension marks an executable file, and how would I create one?

**Comment by cclauss** [comment]
See the discussion of PythonLauncher in section 4.1.1 of https://docs.python.org/2/using/mac.html

Section 4.5 talks about a “Build Applet” tool but it no longer exists.

Probably the best way is to use https://pypi.python.org/pypi/py2app

**Comment by cclauss** [comment]
I did some hacking with py2app and created a standalone Phantom.app which ran as expected until it the `raw_input()` call.  Apps built with py2app send their stdout and stderr to the Mac OSX Console but there does not seem to be any support for stdin. :-(

How are you creating Simple.exe and Python_installer.exe?  If you are using py2exe then you might try adding the following lines to the top of the setup.py file:

```python
# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function, unicode_literals)
```
which should result in a Simple.exe that supports unicode.

**Comment by 671620616** [comment]
Not taking input might indeed be an issue - it's kind of important.  Anyways - I'm using [pyinstaller][0]
and running the following command from the console:

```
C:\...\PhantomChess\Phantom> pyinstaller Run_this.py -F
```

This builds a `Run_this.exe` in the folder `PhantomChess\Phantom\dist\Run_this.exe`, which I then
rename to Simple.exe and move to the top level.

[0]: https://github.com/pyinstaller/pyinstaller/wiki

**Comment by cclauss** [comment]
Can you please try to use PyInstaller to make and run an exe from [`this four line Python script`](https://github.com/pyinstaller/pyinstaller/issues/1240) and see if you get the same result on Windows as I do on the Mac?  If so, please add that as a comment to that PyInstaller issue.

**Comment by 671620616** [comment]
I have done so, and added my results to [the pyinstaller issue][0].  It worked for me, but we somehow
ended up with different encodings - you got utf-8 while I got mbcs (to be honest, I've never heard of 
that).  However and more importantly, when I edited the script to have the chess set white king (♔)
character instead of the ü, it *did* cause an error.

Again, I changed *nothing* except for the character, and it raised a UnicodeError.

[0]: https://github.com/pyinstaller/pyinstaller/issues/1240

**Comment by cclauss** [comment]
I checked in https://github.com/671620616/PhantomChess/blob/master/build_mac_app.sh which works perfectly except for unicode issues so I am going to close this issue but keep issue https://github.com/671620616/PhantomChess/issues/50 open until we can flatten all of our unicode issues.
