### ISSUE TITLE
Pythonista `sk` module?

### ISSUE THREAD

**Issue by 671620616** [671620616/PhantomChess#53]
As the new Pythonista beta was released today, it brought with it a new and improved scene module called `sk`.  I am considerably impressed with it and the new visual editor as well, and am quite interested in moving forward using that.  However I'm hesitant to do so just yet for stability reasons and that it is probably subject to change.  Would it be a good idea to start developing a `sk` version of the GUI but not replace the current `gui_pythonista` folder with it or should I hold off?

**Comment by cclauss** [comment]
I think we have to get the game to play all the way thru without throwing exceptions before focusing more attention on GUI.  Let each try a few side projects to learn the fit and finish of `sk` before rebuilding the Phantom GUI to use it.

**Comment by cclauss** [comment]
Let's leave open but we are not yet in a rush to close it.

**Comment by cclauss** [comment]
I did get rid of MultiScene and used scene.SceneView which should simplify the transition to sk in the future.  Options and Promote are still broken but I will patch them up again.

**Comment by cclauss** [comment]
OK...  GUI should be working again with MultiScene removed and ScreenView in its place.  Do you want to move to sk now before the Pythonista beta is officially released?

**Comment by 671620616** [comment]
Now having a little experience with `sk`, I think it's probably best to begin a new GUI but keep the (new version of) old one in place - I think I've noticed a few bugs in it.  Once it is officially released I think then we can make the switch.

**Comment by cclauss** [comment]
Sounds great.  I created a stub function `game.sk_gui()` and added `sk` as a command in the main loop.  I look forward to what you can create.

**Comment by cclauss** [comment]
https://github.com/671620616/PhantomChess/blob/master/Phantom/sk_gui/create_pieces_sprite_dict.py should help a bit

**Comment by cclauss** [comment]
Up and stumbling in Refactor
