### ISSUE TITLE
Does the anaconda v2.2 upgrade improve our Unicode results?

### ISSUE THREAD

**Issue by cclauss** [671620616/PhantomChess#54]
http://docs.continuum.io/anaconda/changelog.html Upgrades both Python as well as Spyder.

**Comment by 671620616** [comment]
Unfortunately, no.  The results are the same as before - in Spyder, I get unicode characters but not monospaced and in Simple.exe I get SAN characters.

**Comment by cclauss** [comment]
The good news on this one is that the PyInstaller guys accepted my two test cases and reopened my issue so hopefully they will try to fix the issue that PyInstaller sets neither `sys.stdout.encoding` nor `sys.stderr.encoding`.  See: https://github.com/pyinstaller/pyinstaller/issues/1240
