### ISSUE TITLE
Unicode breaks stuff

### ISSUE THREAD

**Issue by 671620616** [671620616/PhantomChess#56]
I know there's already [an issue][0] about unicode, but it's been closed and was originally specifically for Macs, but now it seems to be messing up output on all platforms.  For example, I ran the following code:
```python
import Phantom as P
game = P.ChessGame()
```
and when I entered `game` into the console, it gave me this:
```
      New Game     
â€“â€“â€“â€“â€“â€“â€“â€“â€“â€“â€“â€“â€“â€“â€“â€“â€“â€“â€“
  a b c d e f g h  
8 â™œ â™ž â™� â™› â™š â™� â™ž â™œ 8
7 â™Ÿ â™Ÿ â™Ÿ â™Ÿ â™Ÿ â™Ÿ â™Ÿ â™Ÿ 7
6 â—¦ â€¢ â—¦ â€¢ â—¦ â€¢ â—¦ â€¢ 6
5 â€¢ â—¦ â€¢ â—¦ â€¢ â—¦ â€¢ â—¦ 5
4 â—¦ â€¢ â—¦ â€¢ â—¦ â€¢ â—¦ â€¢ 4
3 â€¢ â—¦ â€¢ â—¦ â€¢ â—¦ â€¢ â—¦ 3
2 â™™ â™™ â™™ â™™ â™™ â™™ â™™ â™™ 2
1 â™– â™˜ â™— â™• â™” â™— â™˜ â™– 1 â—€
  a b c d e f g h   
```

Which is just about as far from a chess board as one can get.  So I think there may be an issue with the way we are encoding characters, maybe fonts as well (monospaced vs. non-monospaced) or even just whether the characters show up at all or raise an error.

[0]: https://github.com/671620616/PhantomChess/issues/50

**Comment by cclauss** [comment]
Please test this on Windows. We should now be encoding the board with cp437 on Windows when printing.

Also make sure that `help` still works from the non-gui menu.

**Comment by 671620616** [comment]
Once again, I have the chess pieces displaying, but they aren't monospaced.

**Comment by cclauss** [comment]
What are SAN characters?

**Comment by 671620616** [comment]
[SAN characters][0] are a way of representing different types of chess pieces using ASCII characters.  

K = king
Q = queen
B = bishop
N = night
P = pawn
R = rook

Capital letters -> white pieces
Lower-case -> black pieces

[0]:http://en.m.wikipedia.org/wiki/Algebraic_notation_(chess)#Naming_the_pieces

**Comment by cclauss** [comment]
Good, SAN characters is the right thing in SImple.exe until PyInstaller fixes their bug.

I loaded up Spyder-Py2.app on my Mac and did `Preferences-->Console-->Display-->Font` and selected `"Menlo"` and the unicode board appeared with proper monospacing.  Of the 10 console fonts available in Spyder-Py2 on the Mac, only `Menlo` displayed the unicode board with proper monospacing.

Is there a similar console font setting in Spyder-Py2.exe?  Do any of the fonts do the right thing?

If that does not do the trick, you can try `Preferences-->Run-->Execute in an external System terminal` or `Run menu-->Configure-->Execute in an external System terminal` but these did not work on Mac OS X.

**Comment by 671620616** [comment]
Unfortunately, `Menlo` is not an option under the Windows version of Spyder.  After trying all the fonts available, none of them had monospaced chess characters.  The `Execute in an external System terminal` simply opened a command prompt that (without further testing) appeared identical to `Simple.exe`.  I believe all the System terminal option does is to execute `$ python PhantomChess/Phantom/Run_this.py`.

Is there a way of changing the font in Python consoles?  If so, I think that might be worth investigating.

**Comment by 671620616** [comment]
I'm not sure in which commit this began but now in Pythonista, `can_print_unicode` returns `False` even though it works as it should.

**Comment by cclauss** [comment]
Perhaps this is the best formulation:

```python
import unicodedata

def can_print_unicode():
    try:
        unicodedata.lookup('WHITE CHESS KING')
        return True
    except KeyError as e:
        return False
```

**Comment by cclauss** [comment]
The new can_print_unicode() should close this issue.
